def mystring(s):
    print("Length:",len(s))
    print("Uppercase:",s.upper())
    print("Lowercase:",s.lower())
    print("Title:",s.title())
    print("Capitalize:",s.capitalize())
    print("is upper:",s.isupper())
    print("is lower:",s.islower())
    print("is title:",s.istitle())
    print("is alpha:",s.isalpha())
    print("is digit:",s.isdigit())
    print("is alnum:",s.isalnum())
def mylist(l):
    print("length:",len(l))
    l.append(50)
    print("append:",l)
    l.extend([10,20,30])
    print("extend:",l)
    l.sort()
    print("sort:",l)
    l.reverse()
    print("reverse:",l)
